# Generated by Django 5.2.14 on 2026-05-19 03:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_uom_many_to_many_business_types'),
        ('tenants', '0004_businesstype_ui_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('applicable_business_types', models.ManyToManyField(blank=True, help_text='Empty = GLOBAL (any tenant vertical). Otherwise only stores whose Client ``business_type`` matches one of these tags may use this tender during checkout.', related_name='applicable_payment_methods', to='tenants.businesstype')),
            ],
            options={
                'verbose_name': 'Payment method',
                'verbose_name_plural': 'Payment methods',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_ref', models.CharField(blank=True, help_text='Processor / reference id (approval code, PSP trace, …).', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='catalog.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_rows', to='sales.paymentmethod')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['order', 'payment_method'], name='sales_order_order_i_72c95f_idx')],
            },
        ),
    ]
