# Generated by Django 5.2.14 on 2026-05-19 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_payment_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('saas', 'SaaS billing'), ('pos', 'POS / storefront')], db_index=True, default='pos', help_text='saas = OmniPOS subscription PSP rails; pos = merchant checkout tenders.', max_length=16)),
                ('merchant_id', models.CharField(blank=True, max_length=255)),
                ('secret_key', models.TextField(blank=True, help_text='Server-side secret only — do not ship to mobile apps.')),
                ('public_key', models.TextField(blank=True, help_text='Publishable / client SDK key surfaced to Flutter.')),
                ('api_extra_credentials', models.JSONField(blank=True, default=dict, help_text='Bank / issuer-specific knobs for instant QR or acquirer adapters (terminal IDs, merchantCategoryCode, issuer payloads…).')),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_gateways', to='sales.paymentmethod')),
            ],
            options={
                'verbose_name': 'Tenant payment gateway',
                'verbose_name_plural': 'Tenant payment gateways',
                'constraints': [models.UniqueConstraint(fields=('payment_method', 'scope'), name='sales_tenant_gateway_unique_payment_method_scope')],
            },
        ),
    ]
