# Generated by Django 5.2.14 on 2026-05-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_fintech_engine"),
        ("payments", "0002_copy_legacy_rows"),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantPaymentGateway',
        ),
    ]
