# Generated by Django 5.2.14 on 2026-05-20 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, help_text='Printed on A4 payloads and referenced as URL when available.', null=True, upload_to='sales/invoices/logos/%Y/%m/')),
                ('tax_identifier', models.CharField(blank=True, help_text='VAT / SSID / Tin (display only).', max_length=128)),
                ('registered_address', models.TextField(blank=True, help_text='Legal / trading address (multi-line plain text).')),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('invoice_footer_note', models.TextField(blank=True, help_text='Disclaimer, bank details, or thank-you footer on formal invoices.')),
                ('default_format', models.CharField(choices=[('A4', 'A4 / PDF-style company invoice'), ('THERMAL', 'POS thermal receipt')], db_index=True, default='A4', help_text='Suggested channel when callers omit explicit format.', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Invoice setting',
                'verbose_name_plural': 'Invoice settings',
                'ordering': ('-updated_at',),
            },
        ),
    ]
