# Generated by Django 5.2.14 on 2026-05-20 14:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoice_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash change returned; reconcile with tendered − amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='tendered_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='POS counter: amount the buyer handed over for this tender (often cash).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
