# Generated by Django 5.2.14 on 2026-05-20 13:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('external_ref', models.CharField(blank=True, db_index=True, help_text='Optional POS / ERP customer key.', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('current_debt', models.DecimalField(decimal_places=2, default=0, help_text='Rolling balance owed by customer (AUDIT snapshot; derive from DebtLedgerEntry for truth).', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='contacts_cust_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('tax_identifier', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('current_payable', models.DecimalField(decimal_places=2, default=0, help_text='Rolling amount owed to supplier (snapshot; reconcile via ledger postings).', max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='contacts_sup_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='contacts.supplier')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
