# Generated by Django 5.2.14 on 2026-05-20 14:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_order_customer'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Receiving branch whose stock ledger is incremented.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='catalog.branch'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='settlement_mode',
            field=models.CharField(choices=[('cash', 'Cash / paid at receipt'), ('credit', 'On supplier AP (increases current_payable)')], db_index=True, default='cash', max_length=16),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='catalog.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contacts.purchaseorder')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['purchase_order', 'product'], name='contacts_pu_purchas_e64e22_idx')],
            },
        ),
    ]
