# Generated by Django 5.2.14 on 2026-05-20 13:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0010_order_customer'),
        ('contacts', '0001_initial'),
        ('sales', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('customer', 'Customer (AR)'), ('supplier', 'Supplier (AP)')], db_index=True, max_length=16)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Increases owed balance for the focal party convention used in OmniPOS postings.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Reliefs / payments applied on account.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_ledger_entries', to='contacts.customer')),
                ('order', models.ForeignKey(blank=True, help_text='POS sales order linkage (customer AR).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_ledger_entries', to='catalog.order')),
                ('order_payment', models.OneToOneField(blank=True, help_text='At most one ledger row per tender line (replay deletes cascade).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_ledger_entry', to='sales.orderpayment')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Purchase-side linkage (supplier AP) when postings exist.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_ledger_entries', to='contacts.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_ledger_entries', to='contacts.supplier')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['party_type', 'created_at'], name='accounting__party_t_6fd4fc_idx'), models.Index(fields=['customer', 'created_at'], name='accounting__custome_97dac2_idx'), models.Index(fields=['supplier', 'created_at'], name='accounting__supplie_469c60_idx'), models.Index(fields=['order', 'created_at'], name='accounting__order_i_0ff58c_idx')],
            },
        ),
    ]
