# Generated by Django 5.2.9 on 2026-05-12 16:40

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('retail', 'Retail'), ('workshop', 'Workshop'), ('services', 'Services')], default='retail', max_length=16)),
                ('custom_domain', models.CharField(blank=True, help_text='Canonical branded hostname (keep in sync with the primary Domain row).', max_length=253, null=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft gate for SaaS provisioning and HTTP access guards.')),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('external_billing_customer_id', models.CharField(blank=True, max_length=255)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='saas.subscriptionplan')),
            ],
            options={
                'ordering': ('schema_name',),
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
        ),
    ]
