# Generated by Django 5.2.14 on 2026-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('schema_name',), 'verbose_name': 'Tenant Client', 'verbose_name_plural': 'Tenant Clients'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Tenant Domain', 'verbose_name_plural': 'Tenant Domains'},
        ),
        migrations.AlterField(
            model_name='client',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('workshop', 'Workshop'), ('services', 'Services')], default='retail', help_text='Drives UX/logic divergence (Retail vs Workshop vs Services) per orchestration.', max_length=16),
        ),
        migrations.AlterField(
            model_name='client',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Canonical branded hostname (mirror the ``Domain.is_primary=True`` row).', max_length=253, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='external_billing_customer_id',
            field=models.CharField(blank=True, help_text='External CRM/customer identifier (Stripe customer id, etc.).', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Operational kill-switch before HTTP access middleware runs.'),
        ),
    ]
