# Generated by Django 5.2.14 on 2026-05-19 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_businesstype_ui_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantKYCApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('saas', 'SaaS billing'), ('pos', 'POS / storefront')], db_index=True, help_text='Whether this packet backs SaaS invoicing credentials or POS acquirer onboarding.', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes requested')], db_index=True, default='draft', max_length=24)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=128)),
                ('tax_identifier', models.CharField(blank=True, max_length=128)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=64)),
                ('registered_address', models.JSONField(blank=True, default=dict, help_text='Structured postal payload for reviewers.')),
                ('documents_requested', models.JSONField(blank=True, default=list, help_text='Checklist issued to merchant (filenames, QR payloads to scan later, …).')),
                ('manual_submission', models.JSONField(blank=True, default=dict, help_text='Operator-entered answers prior to instant QR/bank linking.')),
                ('instant_qr_metadata', models.JSONField(blank=True, default=dict, help_text='Partner QR / issuer callbacks once dynamic rails go live.')),
                ('reviewer_notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_applications', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Merchant KYC application',
                'verbose_name_plural': 'Merchant KYC applications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['client', 'scope', 'status'], name='tenants_mer_client__60af93_idx')],
            },
        ),
    ]
