# Generated by Django 5.2.9 on 2026-05-12 16:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(help_text='Processor identifier such as stripe, paddle, manual.', max_length=64)),
                ('event_type', models.CharField(help_text='Normalized event token, for example invoice_paid.', max_length=128)),
                ('idempotency_key', models.CharField(help_text='Provider-issued or composed key to suppress duplicate ingestion.', max_length=255, unique=True)),
                ('external_object_id', models.CharField(blank=True, help_text='External invoice/session/charge identifier.', max_length=255)),
                ('status', models.CharField(default='received', max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='Event timestamp from upstream when available.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('max_products', models.PositiveIntegerField(help_text='Hard cap per tenant catalog. Use 0 to mean unlimited.')),
                ('max_branches', models.PositiveIntegerField(help_text='Hard cap on active branches/locations per tenant. 0 means unlimited.')),
                ('max_staff', models.PositiveIntegerField(blank=True, help_text='Optional cap on staff profiles. Blank means unlimited.', null=True)),
                ('billing_interval', models.CharField(blank=True, help_text='Suggested interval label (month, year); billing provider owns truth.', max_length=16)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this tier is visible on signup / purchasing flows.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tiers cannot be assigned to newly provisioned tenants.')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
