# Generated by Django 5.2.9 on 2026-05-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='tenants.client'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['tenant', 'created_at'], name='saas_paymen_tenant__fd9b69_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['provider', 'external_object_id'], name='saas_paymen_provide_17d3e2_idx'),
        ),
    ]
