# Generated by Django 5.2.14 on 2026-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='event_type',
            field=models.CharField(help_text='Normalized event token (for example invoice_paid).', max_length=128),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='idempotency_key',
            field=models.CharField(help_text='Dedup anchor for webhooks/commands (provider-scoped uniqueness).', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='recorded_at',
            field=models.DateTimeField(blank=True, help_text='Provider-observed timestamp when available.', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_interval',
            field=models.CharField(blank=True, help_text='Suggested interval label (month, year); upstream billing owns truth.', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive tiers cannot be assigned to freshly provisioned tenants.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this tier is visible on self-serve signup/purchase journeys.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_staff',
            field=models.PositiveIntegerField(blank=True, help_text='Optional cap on staff identities. Blank means unlimited.', null=True),
        ),
    ]
