# Generated by Django 5.2.9 on 2026-05-12 16:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short branch identifier unique within this tenant.', max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Branch-local POS/display configuration payloads.')),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(fields=('code',), name='catalog_branch_code_unique_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('base_uom_code', models.CharField(help_text='Canonical sell/stockkeeping unit.', max_length=32)),
                ('base_uom_precision', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('track_inventory', models.BooleanField(default=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='PostgreSQL-backed JSON payload for expiry, warranties, conversions, etc.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('sku',),
                'constraints': [models.UniqueConstraint(fields=('sku',), name='catalog_product_sku_unique_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='ProductBranchSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sellable', models.BooleanField(db_index=True, default=True, help_text='Allowlist flag for catalogs and POS carts at this branch.')),
                ('branch_selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='When null, callers should fall back to Product.base_price.', max_digits=12, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_overrides', to='catalog.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_settings', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'product'), name='catalog_productbranchsettings_unique_branch_product')],
            },
        ),
    ]
