# Generated by Django 5.2.14 on 2026-05-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='Short identifier unique inside the active tenant.', max_length=64),
        ),
        migrations.AlterField(
            model_name='branch',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Branch-local UX/POS payloads (kitchen routing, receipts, printers, etc.).'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_uom_code',
            field=models.CharField(help_text='Canonical stocking/selling unit (EA, KG, etc.).', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='JSONB-backed extension layer (regulated, electronics, unit conversions …).'),
        ),
        migrations.AlterField(
            model_name='productbranchsettings',
            name='branch_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override list price per branch; falls back to ``Product.base_price`` when null.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productbranchsettings',
            name='is_sellable',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this SKU can be surfaced in POS/UI for this branch.'),
        ),
    ]
