# Generated by Django 5.2.14 on 2026-05-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_order_stock_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_committed',
            field=models.BooleanField(db_index=True, default=False, help_text='When True, branch stock was reduced for this order; cleared after cancel restores.'),
        ),
    ]
