# Generated by Django 5.2.14 on 2026-05-19 03:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_productstock_catalog_state_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Stable unit token (EA, PCS, BOT, KG, …) used alongside Product inventory math.', max_length=64, unique=True)),
                ('label', models.CharField(blank=True, help_text='Human label for POS/UI (optional).', max_length=128)),
                ('applicable_business_type', models.CharField(db_index=True, default='GLOBAL', help_text='GLOBAL for all tenants, or vertical tag aligning with Tenant.business_type (e.g. PHARMACY).', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
