# Generated by Django 5.2.14 on 2026-05-20 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_uom_many_to_many_business_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='Alternate GTIN / scan code (unique within tenant schema when set).', max_length=128, null=True, unique=True)),
                ('alternate_sku', models.CharField(blank=True, db_index=True, help_text='Alternate SKU or pack code (unique when non-blank — see constraint).', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product unit conversion',
                'verbose_name_plural': 'Product unit conversions',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('alternate_sku', ''), _negated=True), fields=('alternate_sku',), name='catalog_productunitconversion_alternate_sku_unique_when_set')],
            },
        ),
    ]
