# Generated by Django 5.2.14 on 2026-05-20 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_unit_conversion'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Buyer for AR tracking (required when tenders include CREDIT).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contacts.customer'),
        ),
    ]
