# Generated by Django 5.2.14 on 2026-05-21 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_order_customer'),
        ('contacts', '0002_purchase_receipt_lines_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated POS user who recorded this sale. Must be set from request.user by server-side checkout / bulk-sync only — never trust client-supplied IDs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'created_by', 'created_at'], name='catalog_ord_branch__ba2eb9_idx'),
        ),
    ]
